version: '3'

services:
  grocy:
    container_name: grocy
    restart: always
    image: linuxserver/grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/shanghai
    volumes:
      - ./config:/config
    ports:
      - 39283:80
  cron:
    build: 
      context: ./docker
      dockerfile: Dockerfile
    container_name: cron
    restart: always
    privileged: true #root权限
    command: 
      - /bin/bash
      - -c
      - |
        cron
        crontab /etc/cron.d/crontab
        tail -f /dev/null
    volumes:
      - .:/workspace
      - ./docker/crontab:/etc/cron.d/crontab
